### ISSUE TITLE
Uglified error message from gapi.auth2.signOut() 

### ISSUE THREAD

**Issue by internationalhouseofdonald** [google/google-api-javascript-client#455]
I can initialize `gapi.auth2` and call `auth2.getAuthInstance()`. I can even log the instance to the console like so:
```
var auth2 = window.gapi.auth2.getAuthInstance();
console.log(auth2);
```

I can see my Google ID under `auth2.currentUser.Ab.El`.
...
But when I try to call `signOut()` with that instance, this message is logged to the console:

`SCRIPT5022: nb`

So, I went back and actually logged the call to `auth2.signOut()` and this is what I got:
```
{
    ...
    rW: Object
    description: "nb"
    message: "nb"
    stack: "Error: nb at tE (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.8bn_hRDDy00.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCNvdNxRyrp158rsgnphVH9ddQ-J1A/cb=gapi.loaded_0:190:33) at Anonymous function (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.8bn_hRDDy00.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCNvdNxRyrp158rsgnphVH9ddQ-J1A/cb=gapi.loaded_0:234:235) at _.C (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.8bn_hRDDy00.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCNvdNxRyrp158rsgnphVH9ddQ-J1A/cb=gapi.loaded_0:108:297) at jF.prototype.BT (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.8bn_hRDDy00.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCNvdNxRyrp158rsgnphVH9ddQ-J1A/cb=gapi.loaded_0:234:208) at a[c] (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.8bn_hRDDy00.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCNvdNxRyrp158rsgnphVH9ddQ-J1A/cb=gapi.loaded_0:215:188) at Anonymous function (http://localhost:8081/main.bundle.js:27020:23) at Anonymous function (https://apis.google.com/js/platform.js:18:210) at Oa (https://apis.google.com/js/platform.js:10:467) at b (https://apis.google.com/js/platform.js:18:188) at E[I] (https://apis.google.com/js/platform.js:18:292)"
}
```

Can anyone tell me what this error means?

My code looks like this: 

```
              window.gapi.load('auth2', function() {
                var auth2 = window.gapi.auth2.init({
                  client_id: 'CLIENT_ID.apps.googleusercontent.com',
                  cookiepolicy: 'single_host_origin',
                });
                if (auth2.isSignedIn.Ab === true) {
                  auth2 = window.gapi.auth2.getAuthInstance();
                } else {
                  auth2 = window.gapi.auth2;
                }
                console.log(auth2);
                console.log(auth2.signOut());
                auth2.signOut().then(function () {
                  // This code is unreachable
                  console.log('User signed out of Google.'); 
                  // Some code here
                }.bind(this));
              }.bind(this));
```

**Comment by internationalhouseofdonald** [comment]
Nevermind. I was creating two instances of the auth singleton. That may not have been my only problem.
