### ISSUE TITLE
[Google Sign In] JS Library throwing an error all of a sudden

### ISSUE THREAD

**Issue by tidusjar** [google/google-api-javascript-client#873]
**Summary**
We are using the `https://accounts.google.com/gsi/client` JS Client to render a Login With Google Button on our user interface.
We have been using this successfully for a very long time, all of a sudden a few days ago the Google Button is not rendering with the following stack trace:

```
ERROR Error
    at _.$e (client:128:335)
    at new rp (client:227:3)
    at aq (client:246:34)
    at No (client:244:246)
    at Object.Oo [as renderButton] (client:216:62)
    at Pe.renderButton (main.b0501b3ff036f102.js:1:4820)
    at e.renderButton (866.e8e180033653210f.js:1:1040)
    at set googleClientId [as googleClientId] (866.e8e180033653210f.js:1:681)
    at wa (main.b0501b3ff036f102.js:1:652227)
    at xs (main.b0501b3ff036f102.js:1:653110)
```

Trying to look around it seems that I am not the only person experiencing this issue:
https://stackoverflow.com/questions/76796549/google-login-ui-crashing

This is happening also on multiple environments across my business.

**Browser(s)/Version(s)**
All

**Expected Behavior**
Login with Google button should render

**Actual Behavior**
Login with Google button does not render

**Steps to Reproduce**
https://stackblitz.com/edit/stackblitz-starters-poqtnt?file=src%2Fmain.ts

**Comment by haru07** [comment]
I have also reported this issue at https://github.com/googlesamples/google-services/issues/581 last week where the button won't render if you have set a width. The configurator also has the same issue. Other people have the same issue. Removing the width property will resolve the issue.

**Comment by areebhashir12** [comment]
put 'px' after 195 
 google.accounts.id.renderButton(buttonElement, {
      type: 'standard',
      theme: 'outline',
      size: 'large',
      width: '195px',
      locale: 'en-us',
    });

**Comment by haru07** [comment]
> put 'px' after 195 google.accounts.id.renderButton(buttonElement, { type: 'standard', theme: 'outline', size: 'large', width: '195px', locale: 'en-us', });

The doc said to use something like width: '400' https://developers.google.com/identity/gsi/web/reference/js-reference#width and it has always work until several days ago. Other people got it to work even without the 'px'. If they updated the api, they should have at least update the doc and the configurator.

**Comment by chrisonline** [comment]
Have the same problem and if I add px to the width it works again.

**Comment by gomezhyuuga** [comment]
Same here, error started to happen on July 25 2023 on my side. Adding the `px` fixed it

**Comment by Melendez34** [comment]
This happen to us at work, using the debugger from Chrome, we found that theres a condition on that requires number type to the width so currently if you remove the '' sigle quotes the button is renders
<img width="979" alt="image" src="https://github.com/google/google-api-javascript-client/assets/62045945/04f7e3d9-0e16-4ecc-84a5-3681caa466b1">
 @jcteo

**Comment by yankovich** [comment]
btw https://accounts.google.com/gsi/client can return different client.js - with and without width value conversion

<img width="1019" alt="Screenshot 2023-08-18 at 12 53 47" src="https://github.com/google/google-api-javascript-client/assets/43784752/554c2ad8-ab94-4bba-b68a-c0584548cd99">


<img width="697" alt="Screenshot 2023-08-18 at 12 56 22" src="https://github.com/google/google-api-javascript-client/assets/43784752/a9df6826-9978-4c7d-9e49-dc47bfa3b240">

maybe this is the cause of the confusion

**Comment by dvanderb** [comment]
This looks like a question about Google Login and Authentication. Please address this question to the google-signin tag on stackoverflow(https://stackoverflow.com/questions/tagged/google-signin)

If you believe this is in error, please reopen the issue.
